# 1. Write a Python Program to Add Two Matrices?
# Answer 

In [1]:
# import numpy
import numpy as np
# randomly generate two matrices
m1 = np.random.randint(1,99,(3,3))
m2 = np.random.randint(1,99,(3,3))

# Do addition of both the matrices
m3 = m1 + m2

# print all the matrics
print('m1 =', m1)
print()
print('m2 =', m2)
print()
print('m3 =', m3)

m1 = [[89  2 78]
 [15 18  6]
 [73 41 78]]

m2 = [[45 41 52]
 [53  2 12]
 [70 19 40]]

m3 = [[134  43 130]
 [ 68  20  18]
 [143  60 118]]


# 2. Write a Python Program to Multiply Two Matrices?
# Answer

In [2]:
# import numpy
import numpy as np

# randomaly generate two matrices
m1 = np.random.randint(65,80,(2,2))
m2 = np.random.randint(40,94,(2,2))

# Do multiplication of both the matrices
m3 = m1@m2

# print all the matrices
print('m1 =', m1)
print()
print('m2 =', m2)
print()
print('m3 =', m3)

m1 = [[75 74]
 [70 79]]

m2 = [[44 66]
 [89 50]]

m3 = [[ 9886  8650]
 [10111  8570]]


# 3. Write a Python Program to Transpose a Matrix?
# Answer

In [3]:
# import numpy
import numpy as np

# randomly generate matrix
m1 = np.random.randint(25,49,(4,5))

# transpose the matrix
m2 = m1.T

# print both the matrices
print('m1 = ', m1)
print()
print('m2 = ', m2)

m1 =  [[39 26 27 45 29]
 [31 31 46 44 48]
 [40 45 44 45 40]
 [42 26 36 36 26]]

m2 =  [[39 31 40 42]
 [26 31 45 26]
 [27 46 44 36]
 [45 44 45 36]
 [29 48 40 26]]


# 4. Write a Python Program to Sort Words in Alphabetic Order?
# Answer 

In [4]:
# import numpy
import numpy as np

# Take a list of alphabetic words
l = ["top", "sort", "Long", "time", "window", "pet", "document", "iNeuron", "Copy"]

# sort the list in alphabetic order
l1 = np.sort(l)

# print the list
print(l1)

['Copy' 'Long' 'document' 'iNeuron' 'pet' 'sort' 'time' 'top' 'window']


# 5. Write a Python Program to Remove Punctuation From a String?
# Answer

In [5]:
# import numpy and string
import numpy as np
import string

# take a string
s = "Wow ! It's an interesting topic."
translator = str.maketrans("","", string.punctuation)
s1 = s.translate(translator)
print(s1)

Wow  Its an interesting topic
