# 1. Write a Python Program to Add Two Matrices?
# Answer 

In [1]:
# import numpy
import numpy as np
# randomly generate two matrices
m1 = np.random.randint(1,99,(3,3))
m2 = np.random.randint(1,99,(3,3))

# Do addition of both the matrices
m3 = m1 + m2

# print all the matrics
print('m1 =', m1)
print()
print('m2 =', m2)
print()
print('m3 =', m3)

m1 = [[25 30 51]
 [ 3 84 67]
 [56 26 39]]

m2 = [[49 78 44]
 [43 33 61]
 [31 29 44]]

m3 = [[ 74 108  95]
 [ 46 117 128]
 [ 87  55  83]]


# 2. Write a Python Program to Multiply Two Matrices?
# Answer

In [2]:
# import numpy
import numpy as np

# randomaly generate two matrices
m1 = np.random.randint(65,80,(2,2))
m2 = np.random.randint(40,94,(2,2))

# Do multiplication of both the matrices
m3 = m1@m2

# print all the matrices
print('m1 =', m1)
print()
print('m2 =', m2)
print()
print('m3 =', m3)

m1 = [[74 71]
 [78 77]]

m2 = [[83 84]
 [45 62]]

m3 = [[ 9337 10618]
 [ 9939 11326]]


# 3. Write a Python Program to Transpose a Matrix?
# Answer

In [3]:
# import numpy
import numpy as np

# randomly generate matrix
m1 = np.random.randint(25,49,(4,5))

# transpose the matrix
m2 = m1.T

# print both the matrices
print('m1 = ', m1)
print()
print('m2 = ', m2)

m1 =  [[39 29 41 29 37]
 [30 36 36 39 26]
 [44 29 40 46 47]
 [45 31 43 28 44]]

m2 =  [[39 30 44 45]
 [29 36 29 31]
 [41 36 40 43]
 [29 39 46 28]
 [37 26 47 44]]


# 4. Write a Python Program to Sort Words in Alphabetic Order?
# Answer 

In [4]:
# import numpy
import numpy as np

# Take a list of alphabetic words
l = ["top", "sort", "Long", "time", "window", "pet", "document", "iNeuron", "Copy"]

# sort the list in alphabetic order
l1 = np.sort(l)

# print the list
print(l1)

['Copy' 'Long' 'document' 'iNeuron' 'pet' 'sort' 'time' 'top' 'window']


# 5. Write a Python Program to Remove Punctuation From a String?
# Answer

In [5]:
# import numpy and string
import numpy as np
import string

# take a string
s = "Wow ! It's an interesting topic."

# remove the punctuation from string
translator = str.maketrans("","", string.punctuation)
s1 = s.translate(translator)

# print the string after removing punctuation
print(s1)

Wow  Its an interesting topic
